apiVersion: v1
kind: BuildConfig
metadata:
  name: mysql
spec:
  output:
    to:
      kind: ImageStreamTag
      name: mysql:latest
  source:
    git:
      uri: https://github.com/yuji-k64613/openshift_mysql.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: debian:jessie
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
