apiVersion: v1
kind: Service
metadata:
  name: mysql-sample
spec:
  ports:
  - name: 3306-tcp
    protocol: TCP
    port: 3306
    targetPort: 3306
nodePort: 0
  selector:
    deploymentconfig: mysql-sample
  type: NodePort
