apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mysql-sample
spec:
  template:
    metadata:
      labels:
        name: mysql-sample
    spec:
      containers:
      - name: mysql-latest
        image: mysql:latest
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: example
        - name: MYSQL_DATABASE
          value: redmine
  replicas: 1
  selector:
    name: mysql-sample
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - mysql-sample-latest
      from:
        kind: ImageStreamTag
        name: mysql:latest
  - type: ConfigChange
